version: '3.8'

# Services
services:
  # Server service
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: shubham4467/mern-backend:v1  
    deploy:
     placement:
       constraints:
        - node.labels.role==backend
    container_name: backend
    ports:
      - "5000:5000"
    env_file: ./.env
    environment:
      - DB_HOST=mongodb
      - DB_USER=$MONGODB_USER
      - DB_PASSWORD=$MONGODB_PASSWORD
      - DB_NAME=$MONGODB_DATABASE
      - DB_PORT=$MONGODB_DOCKER_PORT
    depends_on:
      - mongodb

  # Client service
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: shubham4467/mern-forntend:v1
    deploy:
     placement:
       constraints:
        - node.labels.role==frontend

    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - server

  # Database service
  mongodb:
    image: mongo:latest
    deploy:
     placement:
       constraints:
        - node.labels.role==database
    container_name: mongodb_server
    

    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    ports:
      - "27017:27017"
    volumes:
      - ./../mydata:/data/db

# Volumes define
volumes: 
  mydata:
